/* Fruit Fly Brain — fly.ai MaleCNS web-export worker. Full connectome. */
const ROOT='https://raw.githubusercontent.com/alextitonis/fly.ai/main/world/public/connectome/';
const BRAIN_URL=ROOT+'brain.json',META_URL=ROOT+'meta.bin';
const DT=.020,TAU=.100,DECAY=Math.exp(-DT/TAU),GAIN=3.0,TONIC=.14,THRESHOLD=1,MAX_SAMPLE=1800,TICK_MS=80;
let N=0,E=0,lnMin=0,indptr,targets,qcodes,V,fired,types=[],classes=[],typeIdx,classIdx,side,aliasMask;
let aliasSamples={},running=false,stimuli={},tickNo=0;
const ALIASES=['VIS_ME','VIS_LPTC','VIS_LO','OLF_ORN_FOOD','MECH_BRISTLE','MECH_JO','CX_PFN','CX_FC','CX_HDELTA','GNG_DESC','VNC_CPG'];
async function getJson(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw Error('Fetch failed: HTTP '+r.status);return r.json()}
async function getBinary(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw Error('Fetch failed: HTTP '+r.status);return r.arrayBuffer()}
function readVarint(bytes,p){let v=0,s=0,b;do{if(p>=bytes.length)throw Error('Unexpected end of connectome varints');b=bytes[p++];v+=(b&127)*2**s;s+=7;if(s>35)throw Error('Invalid connectome varint')}while(b&128);return[v>>>0,p]}
function parseMeta(buf){const d=new DataView(buf);if(d.byteLength<16||d.getUint32(0,false)!==0x464c594d)throw Error('Invalid fly.ai meta header');const n=d.getUint32(8,true),len=d.getUint32(12,true);if(n!==N)throw Error(`Metadata neuron count ${n} does not match weights ${N}`);const header=JSON.parse(new TextDecoder().decode(new Uint8Array(buf,16,len)));let p=16+len;typeIdx=new Uint16Array(buf.slice(p,p+n*2));p+=n*2;classIdx=new Uint8Array(buf.slice(p,p+n));p+=n;side=new Uint8Array(buf.slice(p,p+n));types=header.types;classes=header.superclasses}
function decodeWeights(buf){const bytes=new Uint8Array(buf),d=new DataView(buf);if(d.byteLength<20||d.getUint32(0,false)!==0x464c5957)throw Error('Invalid fly.ai weight header');const version=d.getUint32(4,true);if(version!==1)throw Error('Unsupported fly.ai weight version '+version);N=d.getUint32(8,true);E=d.getUint32(12,true);lnMin=d.getFloat32(16,true);let p=20;indptr=new Uint32Array(N+1);let acc=0;for(let i=0;i<N;i++){const r=readVarint(bytes,p);indptr[i]=acc;acc+=r[0];p=r[1]}indptr[N]=acc;if(acc!==E)throw Error(`Connectome edge count mismatch: decoded ${acc}, expected ${E}`);targets=new Uint32Array(E);for(let i=0;i<N;i++){let absolute=0;for(let e=indptr[i];e<indptr[i+1];e++){const r=readVarint(bytes,p);p=r[1];absolute=e===indptr[i]?r[0]:absolute+r[0];targets[e]=absolute}}if(p+E>bytes.length)throw Error('Connectome weight payload is truncated');qcodes=new Uint8Array(E);qcodes.set(bytes.subarray(p,p+E))}
function typeNamesFor(i){return[types[typeIdx[i]]||'',classes[classIdx[i]]||'']}
function matchAlias(a,i){const[t,c]=typeNamesFor(i),s=(t+' '+c).toLowerCase();if(a==='VIS_ME')return t==='LC10a'||s.includes('lc10a');if(a==='VIS_LPTC')return t==='LC4'||t==='LPLC2'||s.includes('lc4')||s.includes('lplc2');if(a==='VIS_LO')return t==='LPLC1'||s.includes('lplc1');if(a==='OLF_ORN_FOOD')return s.includes('orn')||s.includes('olfactory');if(a==='MECH_BRISTLE')return s.includes('mechanosensory')||s.includes('bristle')||s.includes('mechanoreceptor');if(a==='MECH_JO')return s.includes('johnston');if(a==='CX_PFN')return s.includes('pfn');if(a==='CX_FC')return s.includes('fan-shaped')||s.includes('fan_shaped');if(a==='CX_HDELTA')return s.includes('hdelta');if(a==='GNG_DESC')return c==='descending_neuron'||s.includes('dng100')||s.includes('dng');if(a==='VNC_CPG')return s.includes('dng100')||s.includes('motor')||s.includes('vnc');return false}
function buildSamples(){aliasSamples={};aliasMask=new Uint16Array(N);for(const a of ALIASES)aliasSamples[a]=[];for(let i=0;i<N;i++)for(let g=0;g<ALIASES.length;g++)if(aliasSamples[ALIASES[g]].length<MAX_SAMPLE&&matchAlias(ALIASES[g],i)){aliasSamples[ALIASES[g]].push(i);aliasMask[i]|=1<<g}}
function stimulateAlias(n,x){const idx=aliasSamples[n]||[];for(let k=0;k<idx.length;k++)V[idx[k]]+=x}
function applyStim(){for(const[n,x]of Object.entries(stimuli))stimulateAlias(n,Number(x)||0)}
function weight(e){const code=qcodes[e]&127;return Math.exp(lnMin*(1-code/127))*((qcodes[e]&128)?-1:1)}
function step(){applyStim();for(let i=0;i<N;i++)V[i]=V[i]*DECAY+TONIC*(1-DECAY);for(let k=0;k<fired.length;k++){const pre=fired[k];for(let e=indptr[pre];e<indptr[pre+1];e++)V[targets[e]]+=GAIN*weight(e)}const next=[];const groups=new Uint32Array(ALIASES.length);for(let i=0;i<N;i++)if(V[i]>=THRESHOLD){V[i]=0;next.push(i);const mask=aliasMask[i];for(let g=0;g<ALIASES.length;g++)if(mask&(1<<g))groups[g]++}fired=next;tickNo++;self.postMessage({type:'tick',total:next.length,groups:Array.from(groups),tick:tickNo})}
async function init(){self.postMessage({type:'status',message:'Loading fly.ai brain metadata…'});const info=await getJson(BRAIN_URL);N=info.neurons;E=info.connections;parseMeta(await getBinary(META_URL));let buffers=[];for(let i=0;i<info.parts.length;i++){self.postMessage({type:'status',message:`Downloading brain weights ${i+1}/${info.parts.length} (${Math.round(info.weights_mb)} MB total)…`});buffers.push(new Uint8Array(await getBinary(ROOT+info.parts[i])))}const total=buffers.reduce((n,b)=>n+b.byteLength,0);let joined=new Uint8Array(total);let p=0;for(const b of buffers){joined.set(b,p);p+=b.byteLength}buffers.length=0;self.postMessage({type:'status',message:'Decoding full 166,700-neuron connectome…'});decodeWeights(joined.buffer);joined=null;buildSamples();V=new Float32Array(N);fired=[];self.postMessage({type:'ready',neurons:N,connections:E,groups:ALIASES,engine:'fly.ai web export',weightError:info.weight_error_mean})}
self.onmessage=async e=>{const m=e.data;try{if(m.type==='init'&&!N)await init();else if(m.type==='stimuli')stimuli=m.stimuli||{};else if(m.type==='reset'){if(V)V.fill(0);fired=[];tickNo=0}else if(m.type==='start'&&!running){running=true;loop()}else if(m.type==='stop')running=false}catch(err){running=false;self.postMessage({type:'error',message:err.message||String(err)})}};
function loop(){if(!running)return;const t=performance.now();step();setTimeout(loop,Math.max(1,TICK_MS-(performance.now()-t)))}
