/* Fruit Fly Brain Arena — reliable canvas game. Brain runs independently in brain-worker.js. */
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),brainCanvas=$('brainCanvas'),bctx=brainCanvas.getContext('2d');
const W=1200,H=720,WORLD=1800;
const state={playerHP:100,flyHP:100,score:0,wave:1,over:false,defending:false,dash:0,attack:0,brain:0,brainOnline:false,brainTick:0};
const player={x:WORLD/2,z:WORLD/2+360,r:24,vx:0,vz:0,speed:300,inv:0};
const fly={x:WORLD/2,z:WORLD/2-120,r:42,vx:0,vz:0,heading:0,flap:0,phase:0,attack:0};
const keys=new Set(),stick={x:0,y:0};let stickId=null,worker=null,last=performance.now(),stimTimer=0,shake=0;
const foods=Array.from({length:14},(_,i)=>({x:180+(i*257)%1440,z:150+(i*389)%1100,r:13,alive:true,pulse:i*.8}));
const particles=[];const stars=Array.from({length:100},()=>({x:Math.random()*WORLD,z:Math.random()*WORLD,r:1+Math.random()*2,a:.15+Math.random()*.5}));
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(canvas.clientWidth*d);canvas.height=Math.floor(Math.max(360,canvas.clientHeight)*d);brainCanvas.width=Math.floor(brainCanvas.clientWidth*d);brainCanvas.height=Math.floor(Math.max(150,brainCanvas.clientHeight)*d);draw();drawBrain()}
addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,100));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
function normBrain(name){const i=state.groups?.indexOf(name);return i>=0?Math.min(1,(state.spikes?.[i]||0)/120):0}
function spawnBurst(x,z,text){for(let i=0;i<14;i++){const a=Math.random()*Math.PI*2,s=50+Math.random()*180;particles.push({x,z,vx:Math.cos(a)*s,vz:Math.sin(a)*s,life:.5+Math.random()*.5,text:i===0?text:''})}}
function moveInput(){let x=stick.x,y=stick.y;if(!x&&!y){if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;if(keys.has('w')||keys.has('arrowup'))y--;if(keys.has('s')||keys.has('arrowdown'))y++}const l=Math.hypot(x,y);return l>1?{x:x/l,y:y/l}:{x,y}}
function attack(){if(state.over||state.attack>0)return;state.attack=.28;const d=dist(player,fly);if(d<145){const dmg=state.defending?10:18;state.flyHP=Math.max(0,state.flyHP-dmg);state.score+=dmg;shake=8;spawnBurst(fly.x,fly.z,'HIT!');if(state.flyHP<=0){state.score+=250;state.wave++;state.flyHP=100;fly.x=250+Math.random()*1300;fly.z=180+Math.random()*900;spawnBurst(fly.x,fly.z,'NEW WAVE')}}else{brainStim({MECH_BRISTLE:2.2});spawnBurst(player.x,player.z,'MISS')};ui()}
function defend(){if(state.over)return;state.defending=true;clearTimeout(defend.timer);defend.timer=setTimeout(()=>state.defending=false,650)}
function dash(){if(state.over||state.dash>0)return;state.dash=.9;const m=moveInput(),l=Math.hypot(m.x,m.y)||1;player.x=clamp(player.x+m.x/l*190,40,WORLD-40);player.z=clamp(player.z+m.y/l*190,40,WORLD-40);player.inv=.28;spawnBurst(player.x,player.z,'DASH')}
function brainAbility(){if(state.over||state.brain>0)return;state.brain=1.3;state.score+=10;brainStim({MECH_BRISTLE:3,VIS_LPTC:2,VIS_ME:1.5});spawnBurst(fly.x,fly.z,'NEURAL PULSE')}
function reset(){state.playerHP=100;state.flyHP=100;state.score=0;state.wave=1;state.over=false;state.defending=false;state.dash=0;state.attack=0;state.brain=0;state.brainOnline=false;player.x=WORLD/2;player.z=WORLD/2+360;player.inv=0;fly.x=WORLD/2;fly.z=WORLD/2-120;fly.vx=fly.vz=0;foods.forEach(f=>f.alive=true);particles.length=0;$('message').classList.add('hidden');brainStim({});ui()}
function end(win){state.over=true;$('message').textContent=win?'🧠 You defeated the brain-driven fly!':'🪰 The fly defeated you — press R or Reset to try again.';$('message').classList.remove('hidden')}
function brainStim(s){if(worker)try{worker.postMessage({type:'stimuli',stimuli:s})}catch(_){} }
function sendSensory(){if(!state.brainOnline)return;stimTimer-=1/60;if(stimTimer>0)return;stimTimer=.10;const d=dist(player,fly),threat=clamp(1-d/700,0,1),food=foods.find(f=>f.alive),fd=food?dist(fly,food):999;brainStim({VIS_ME:.05+threat*.9,VIS_LPTC:threat,VIS_LO:threat*.4,OLF_ORN_FOOD:clamp(1-fd/700,0,1),MECH_BRISTLE:d<180?1.5:0,MECH_JO:.08})}
function updateFly(dt){const d=dist(player,fly),brainThreat=normBrain('VIS_LPTC')*.7+normBrain('MECH_BRISTLE')*.3,approach=normBrain('CX_PFN')*.45+normBrain('CX_FC')*.3+normBrain('OLF_ORN_FOOD')*.25,turn=normBrain('CX_HDELTA');let tx=0,tz=0;if(d<760){tx=(player.x-fly.x)/(d||1);tz=(player.z-fly.z)/(d||1)}const food=foods.find(f=>f.alive);if(food&&approach>.1&&d>260){const fd=dist(fly,food);if(fd){tx=(food.x-fly.x)/fd;tz=(food.z-fly.z)/fd}}if(brainThreat>.22||d<240){tx=-tx;tz=-tz}fly.heading+=((turn-.08)*2.5+(Math.random()-.5)*.35)*dt;const hx=Math.cos(fly.heading),hz=Math.sin(fly.heading);tx=tx*.7+hx*.3;tz=tz*.7+hz*.3;const l=Math.hypot(tx,tz)||1;tx/=l;tz/=l;const speed=90+approach*110+brainThreat*100;fly.vx+=(tx*speed-fly.vx)*Math.min(1,dt*2.5);fly.vz+=(tz*speed-fly.vz)*Math.min(1,dt*2.5);fly.x+=fly.vx*dt;fly.z+=fly.vz*dt;fly.x=clamp(fly.x,80,WORLD-80);fly.z=clamp(fly.z,80,WORLD-80);fly.flap+=dt*22;fly.phase+=dt*4;fly.attack=Math.max(0,fly.attack-dt);if(d<95&&fly.attack<=0&&!state.over){fly.attack=.8;state.playerHP=Math.max(0,state.playerHP-(state.defending?4:13));player.inv=.3;shake=7;spawnBurst(player.x,player.z,'-HP');if(state.playerHP<=0)end(false)}}
function update(dt){if(state.over)return;const m=moveInput();if(m.x||m.y){const l=Math.hypot(m.x,m.y);player.vx+=(m.x/l*player.speed-player.vx)*Math.min(1,dt*12);player.vz+=(m.y/l*player.speed-player.vz)*Math.min(1,dt*12)}else{player.vx*=Math.max(0,1-dt*10);player.vz*=Math.max(0,1-dt*10)}player.x=clamp(player.x+player.vx*dt,40,WORLD-40);player.z=clamp(player.z+player.vz*dt,40,WORLD-40);player.inv=Math.max(0,player.inv-dt);state.attack=Math.max(0,state.attack-dt);state.dash=Math.max(0,state.dash-dt);state.brain=Math.max(0,state.brain-dt);updateFly(dt);foods.forEach(f=>{f.pulse+=dt;if(f.alive&&dist(fly,f)<42){f.alive=false;state.score+=15;spawnBurst(f.x,f.z,'+15')}});if(foods.every(f=>!f.alive))foods.forEach(f=>f.alive=true);particles.forEach(p=>{p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=.96;p.vz*=.96;p.life-=dt});for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);sendSensory();ui()}
function worldToScreen(x,z){const dpr=Math.min(devicePixelRatio||1,2),scale=Math.min(canvas.width/W,canvas.height/H),ox=(canvas.width-W*scale)/2,oy=(canvas.height-H*scale)/2;return{x:ox+x/WORLD*W*scale,y:oy+z/WORLD*H*scale,s:scale}}
function draw(){const dpr=Math.min(devicePixelRatio||1,2),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#07121c';ctx.fillRect(0,0,w,h);const scale=Math.min(w/W,h/H),ox=(w-W*scale)/2,oy=(h-H*scale)/2;ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.fillStyle='#0a1d22';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(55,220,165,.12)';ctx.lineWidth=1;for(let x=0;x<=W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<=H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}stars.forEach(s=>{ctx.globalAlpha=s.a;ctx.fillStyle='#9be7ff';ctx.beginPath();ctx.arc(s.x/WORLD*W,s.z/WORLD*H,s.r,0,7);ctx.fill()});ctx.globalAlpha=1;
  foods.forEach(f=>{if(!f.alive)return;const p=worldToScreen(f.x,f.z);const x=f.x/WORLD*W,y=f.z/WORLD*H,r=13+Math.sin(f.pulse*3)*2;ctx.fillStyle='rgba(255,120,50,.15)';ctx.beginPath();ctx.arc(x,y,r+12,0,7);ctx.fill();ctx.fillStyle='#ff713f';ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.fillStyle='#6b381e';ctx.fillRect(x-2,y-r-5,4,8)});
  drawFly();drawPlayer();particles.forEach(p=>{const x=p.x/WORLD*W,y=p.z/WORLD*H;ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle='#9df5ff';ctx.beginPath();ctx.arc(x,y,3+p.life*3,0,7);ctx.fill();if(p.text){ctx.font='bold 14px system-ui';ctx.fillText(p.text,x+7,y-7)}});ctx.globalAlpha=1;ctx.strokeStyle='#38e8a4';ctx.lineWidth=5;ctx.strokeRect(8,8,W-16,H-16);ctx.restore();if(shake>0){shake*=.9;if(shake<.2)shake=0}}
function drawFly(){const x=fly.x/WORLD*W,y=fly.z/WORLD*H,fl=.35+Math.abs(Math.sin(fly.flap))*1.05,ang=Math.atan2(fly.vz,fly.vx);ctx.save();ctx.translate(x,y);ctx.rotate(ang);ctx.globalAlpha=.28;ctx.fillStyle='#d8f7ff';ctx.beginPath();ctx.ellipse(-8,-30,48*fl,13,0,0,7);ctx.ellipse(-8,30,48*fl,13,0,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#2c3035';ctx.beginPath();ctx.ellipse(0,0,36,27,0,0,7);ctx.fill();ctx.fillStyle='#121418';ctx.beginPath();ctx.ellipse(29,0,22,20,0,0,7);ctx.fill();ctx.fillStyle='#c34cff';ctx.beginPath();ctx.arc(39,-9,7,0,7);ctx.arc(39,9,7,0,7);ctx.fill();ctx.restore();ctx.fillStyle='#111';ctx.fillRect(x-45,y-52,90,7);ctx.fillStyle='#ff537f';ctx.fillRect(x-45,y-52,90*(state.flyHP/100),7)}
function drawPlayer(){const x=player.x/WORLD*W,y=player.z/WORLD*H;ctx.save();ctx.translate(x,y);if(player.inv>0&&Math.floor(player.inv*20)%2===0)ctx.globalAlpha=.45;ctx.fillStyle=state.defending?'#8bd0ff':'#35a8ff';ctx.beginPath();ctx.arc(0,0,24,0,7);ctx.fill();ctx.fillStyle='#dff7ff';ctx.beginPath();ctx.arc(-7,-7,6,0,7);ctx.fill();if(state.defending){ctx.strokeStyle='#8bd0ff';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,38,0,7);ctx.stroke()}if(state.attack>0){ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,65,-.7,.7);ctx.stroke()}ctx.restore();ctx.fillStyle='#111';ctx.fillRect(x-42,y+38,84,7);ctx.fillStyle='#35e69f';ctx.fillRect(x-42,y+38,84*(state.playerHP/100),7)}
function drawBrain(){const w=brainCanvas.width,h=brainCanvas.height;bctx.clearRect(0,0,w,h);bctx.fillStyle='#06101a';bctx.fillRect(0,0,w,h);const names=state.groups||['VIS_ME','VIS_LPTC','VIS_LO','OLF_ORN_FOOD','MECH_BRISTLE','MECH_JO','CX_PFN','CX_FC','CX_HDELTA','GNG_DESC','VNC_CPG'];names.forEach((n,i)=>{const v=normBrain(n),bw=Math.max(3,w/names.length-5),bh=v*(h-34);bctx.fillStyle=v>.2?'#ff5c8a':'#38e8a4';bctx.fillRect(i*w/names.length+2,h-25-bh,bw,bh);bctx.fillStyle='#9fb5c8';bctx.font=`${Math.max(8,10*(devicePixelRatio||1))}px system-ui`;bctx.save();bctx.translate(i*w/names.length+2,h-5);bctx.rotate(-.35);bctx.fillText(n.replace('OLF_ORN_','').replace('MECH_',''),0,0);bctx.restore()})}
function ui(){$('playerHealth').textContent=Math.ceil(state.playerHP);$('flyHealth').textContent=Math.ceil(state.flyHP);$('score').textContent=state.score;$('brainState').textContent=state.brainOnline?(normBrain('VIS_LPTC')>.2?'ALERT':'ACTIVE'):'OFFLINE';$('neurons').textContent=state.brainOnline?`${state.brainTick.toLocaleString()} spikes / neural tick`:'Game playable while brain loads…'}
function stickMove(e){const r=$('joystick').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.38,dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy)||1,k=Math.min(1,max/l);stick.x=dx/max*k;stick.y=dy/max*k;$('stick').style.transform=`translate(${dx*k}px,${dy*k}px)`}
function resetStick(){stick.x=stick.y=0;stickId=null;const s=$('stick');if(s)s.style.transform='translate(0,0)'}
const joy=$('joystick');joy.addEventListener('pointerdown',e=>{e.preventDefault();stickId=e.pointerId;joy.setPointerCapture?.(e.pointerId);stickMove(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===stickId){e.preventDefault();stickMove(e)}});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>joy.addEventListener(ev,e=>{if(e.pointerId===stickId)resetStick()}));
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(e.code==='Space'){e.preventDefault();attack()}if(k==='q')brainAbility();if(k==='e')defend();if(k==='shift')dash();if(k==='r')reset()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('reset').addEventListener('click',reset);$('attackTouch').addEventListener('pointerdown',e=>{e.preventDefault();attack()});$('defendTouch').addEventListener('pointerdown',e=>{e.preventDefault();defend()});$('dashTouch').addEventListener('pointerdown',e=>{e.preventDefault();dash()});$('abilityTouch').addEventListener('pointerdown',e=>{e.preventDefault();brainAbility()});
function initBrain(){try{worker=new Worker('./brain-worker.js');worker.onmessage=e=>{const m=e.data;if(m.type==='status'){$('brainStatus').textContent=m.message}else if(m.type==='error'){$('brainStatus').textContent='Brain unavailable: '+m.message;state.brainOnline=false;ui()}else if(m.type==='ready'){state.brainOnline=true;state.groups=m.groups;state.spikes=new Array(m.groups.length).fill(0);$('brainStatus').textContent=`REAL CONNECTOME ONLINE · ${m.neurons.toLocaleString()} neurons · ${m.connections.toLocaleString()} connections`;worker.postMessage({type:'start'});ui()}else if(m.type==='tick'){state.spikes=m.groups;state.brainTick=m.total;drawBrain();}};worker.postMessage({type:'init'})}catch(e){$('brainStatus').textContent='Brain worker unavailable — game still playable.'}}
reset();resize();initBrain();
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
